### ISSUE TITLE
npm install aws-lambda-ric --save throwing error 

### ISSUE THREAD

**Issue by RRobbins94** [aws/aws-lambda-nodejs-runtime-interface-client#3]
When trying to npm install aws-lambda-ric --save, the following error is thrown:

1606 verbose stack Error: aws-lambda-ric@1.0.0 preinstall: `./scripts/preinstall.sh`
1606 verbose stack Exit status 1
1606 verbose stack     at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
1606 verbose stack     at EventEmitter.emit (events.js:189:13)
1606 verbose stack     at ChildProcess.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1606 verbose stack     at ChildProcess.emit (events.js:189:13)
1606 verbose stack     at maybeClose (internal/child_process.js:970:16)
1606 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
1607 verbose pkgid aws-lambda-ric@1.0.0
1608 verbose cwd C:\Users\User\source\repos\aws-lambda-container\myProj\hello-world
1609 verbose Windows_NT 10.0.18363
1610 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "aws-lambda-ric" "--save"
1611 verbose node v10.15.3
1612 verbose npm  v6.14.9
1613 error code ELIFECYCLE
1614 error errno 1
1615 error aws-lambda-ric@1.0.0 preinstall: `./scripts/preinstall.sh`
1615 error Exit status 1
1616 error Failed at the aws-lambda-ric@1.0.0 preinstall script.
1616 error This is probably not a problem with npm. There is likely additional logging output above.
1617 verbose exit [ 1, true ]

**Comment by dfee** [comment]
Getting the same error – albeit on alpine:
```
2018 verbose lifecycle aws-lambda-ric@1.0.0~preinstall: unsafe-perm in lifecycle false
2019 verbose lifecycle aws-lambda-ric@1.0.0~preinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/aws-lambda-ric/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2020 verbose lifecycle aws-lambda-ric@1.0.0~preinstall: CWD: /usr/local/lib/node_modules/aws-lambda-ric
2021 silly lifecycle aws-lambda-ric@1.0.0~preinstall: Args: [ '-c', './scripts/preinstall.sh' ]
2022 silly lifecycle aws-lambda-ric@1.0.0~preinstall: Returned: code: 1  signal: null
2023 info lifecycle aws-lambda-ric@1.0.0~preinstall: Failed to exec preinstall script
2024 timing action:preinstall Completed in 78ms
2025 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
2026 timing stage:rollbackFailedOptional Completed in 212ms
2027 timing stage:runTopLevelLifecycles Completed in 4769ms
2028 verbose stack Error: aws-lambda-ric@1.0.0 preinstall: `./scripts/preinstall.sh`
2028 verbose stack Exit status 1
2028 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2028 verbose stack     at EventEmitter.emit (events.js:315:20)
2028 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2028 verbose stack     at ChildProcess.emit (events.js:315:20)
2028 verbose stack     at maybeClose (internal/child_process.js:1021:16)
2028 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2029 verbose pkgid aws-lambda-ric@1.0.0
2030 verbose cwd /
2031 verbose Linux 4.19.121-linuxkit
2032 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "aws-lambda-ric"
2033 verbose node v12.18.4
2034 verbose npm  v6.14.6
2035 error code ELIFECYCLE
2036 error errno 1
2037 error aws-lambda-ric@1.0.0 preinstall: `./scripts/preinstall.sh`
2037 error Exit status 1
2038 error Failed at the aws-lambda-ric@1.0.0 preinstall script.
2038 error This is probably not a problem with npm. There is likely additional logging output above.
2039 verbose exit [ 1, true ]
```

**Comment by ariel-frischer** [comment]
Yarn installation on windows 10 gives me this:
```
error C:\Users\Ariel\initiate-video\backend\node_modules\aws-lambda-ric: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\Ariel\initiate-video\backend\node_modules\aws-lambda-ric
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@12.19.0 | win32 | x64
gyp info find Python using Python version 3.6.8 found at "C:\Users\Ariel\AppData\Local\Programs\Python\Python36\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Ariel\initiate-video\backend\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Ariel\initiate-video\backend\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Ariel\initiate-video\backend\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\Ariel\initiate-video\backend\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Ariel\initiate-video\backend\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\Ariel\initiate-video\backend\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Ariel\initiate-video\backend\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ariel\\initiate-video\\backend\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ariel\initiate-video\backend\node_modules\aws-lambda-ric

```

**Comment by donnes** [comment]
Any update about this bug?

**Comment by alexying2110** [comment]
I was seeing the same issue on `pandoc/ubuntu-latex`. referring to #12 and adding the missing packages seemed to have resolved this.

**Comment by retatu** [comment]
any update?

**Comment by tejas-contentstack** [comment]
@RRobbins94  To get this working in Windows 10, I used WSL ubuntu distro.

- `sudo apt install -y build-essential make cmake autoconf automake libtool m4 python3 unzip libssl-dev libcurl4-openssl-dev`
- `npm i` 

Also, I was facing an issue with Libcuda.so.1 symbolic link creation. To fix that either follow 
- https://superuser.com/questions/1707681/wsl-libcuda-is-not-a-symbolic-link
OR 
- https://github.com/microsoft/WSL/issues/5548#issuecomment-912495487
